apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubearmor-test
  template:
    metadata:
      labels:
        app: kubearmor-test
    spec:
      containers:
        - name: kubearmor-test
          image: thisisommore/kubearmor_test:latest
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
