name: Deploy to Kind with KubeArmor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Kind cluster
      uses: helm/kind-action@v1.4.0
      with:
        version: v0.18.0
        cluster_name: my-cluster
        wait: 300s
        kubectl_version: v1.23.12

    # Install karmor cli tool
    - name: Install KubeArmor CLI tool
      run: |
        curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin

    # Install KubeArmor in the cluster
    - name: Install KubeArmor in the cluster
      run: |
        sudo karmor install

    # Deploy KubeArmor policies
    - name: Deploy KubeArmor policies
      run: |
        kubectl apply -f cat-echo-block.yml

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push your Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: thisisommore/kind_test:latest

    # Load the Docker image into the Kind cluster
    - name: Load Docker image into Kind cluster
      run: |
        docker pull thisisommore/kind_test:latest
        kind load docker-image thisisommore/kind_test:latest --name my-cluster

    # Deploy your application to the Kind cluster
    - name: Deploy to Kind cluster
      run: |
        kubectl apply -f deployment.yml

    # Wait for 12 seconds to generate KubeArmor summary
    - name: Generate KubeArmor summary
      run: |
        sleep 12
        karmor summary

    # Add your test steps or any other actions you need to perform after deployment
