name: Deploy to K3s with KubeArmor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create K3s cluster
      run: |
        sudo curl -sfL https://get.k3s.io | sudo sh -
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        sudo chown $USER:$USER /etc/rancher/k3s/k3s.yaml
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        kubectl get nodes


    # Install karmor cli tool
    - name: Install KubeArmor CLI tool
      run: |
        curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin

    # Install KubeArmor in the cluster
    - name: Install KubeArmor in the cluster
      run: |
        sudo karmor install

    # Deploy KubeArmor policies
    - name: Deploy KubeArmor policies
      run: |
        kubectl apply -f cat-echo-block.yml

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push your Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: thisisommore/kubearmor_test:latest

    # Load the Docker image into the K3s cluster
    - name: Load Docker image into K3s cluster
      run: |
        docker pull thisisommore/kubearmor_test:latest
        k3s ctr images import thisisommore/kubearmor_test:latest

    # Deploy your application to the K3s cluster
    - name: Deploy to K3s cluster
      run: |
        kubectl apply -f deployment.yml

    # Wait for 12 seconds to generate KubeArmor summary
    - name: Generate KubeArmor summary
      run: |
        sleep 12
        karmor summary

    # Add your test steps or any other actions you need to perform after deployment
