name: Deploy to K3s with KubeArmor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create K3s cluster
      run: |
        sudo RUNTIME=docker bash -c "$(curl -sfL https://raw.githubusercontent.com/kubearmor/KubeArmor/main/contribution/k3s/install_k3s.sh)"
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        sudo chown $USER:$USER /etc/rancher/k3s/k3s.yaml
        kubectl get nodes

    # Install karmor cli tool
    - name: Install KubeArmor CLI tool
      run: |
        curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin


    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push your Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: thisisommore/kubearmor_test:latest

    # Deploy your application to the K3s cluster
    - name: Deploy to K3s cluster
      run: |
        kubectl apply -f deployment.yml
        sleep 8
        kubectl describe po -l app="kubearmor-test"
        
    # Install KubeArmor in the cluster
    - name: Install KubeArmor in the cluster
      run: |
        sudo karmor install
        kubectl apply -f https://raw.githubusercontent.com/kubearmor/discovery-engine/dev/deployments/k8s/deployment.yaml
        sleep 10
    # Deploy KubeArmor policies
    - name: Deploy KubeArmor policies
      run: |
        sleep 10
        kubectl apply -f cat-echo-block.yml

    # Wait for 12 seconds to generate KubeArmor summary
    - name: Generate KubeArmor summary
      run: |
        sleep 12
        sudo apt-get update && sudo apt-get install -y socat
        karmor summary
    # Add your test steps or any other actions you need to perform after deployment
