name: Deploy to KIND

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: thisisommore/app-name:${{ github.sha }}

    - name: Set up KIND
      uses: engineerd/setup-kind@v0.5.0

    - name: Create KIND cluster
      run: |
        kind create cluster --name test-cluster

    - name: Update deployment.yaml with the image tag
      run: |
        sed -i 's|thisisommore/kubearmor_test:latest|thisisommore/kubearmor_test:${{ github.sha }}|g' deployment.yaml

    - name: Deploy app to KIND cluster
      run: |
        kubectl cluster-info --context kind-test-cluster
        kubectl apply -f deployment.yaml

    # - name: Test app on KIND cluster
    #   run: |
    #     # Add your test commands here. For example:
    #     kubectl wait --for=condition=available --timeout=120s deployment/your-app-deployment
    #     # You can also use tools like curl or wget to send HTTP requests to your app, or run integration tests.

    - name: Delete KIND cluster
      run: |
        kind delete cluster --name test-cluster
